### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by funcrab** [Omochice/deepl-translate-cli#6]
Environment:
- Arch Linux (Manjaro-sway)
- Kernel: 5.10.18-zen-1-zen-lts510-g513e3c94a40f

The result is as follows
```
$ echo "hello" | deepl-translate-cli --stdin
2021/09/21 22:52:56 unexpected end of JSON input
$ cat -neT $HOME/.config/deepl-translate-cli/setting.json
     1	{$
     2	  "source_lang": "EN",$
     3	  "target_lang": "JA"$
     4	}$
$
```
Specification change for deepl?

**Comment by Omochice** [comment]
The error occurs when trying to load an invalid json.
But the presented json file looks like a ​valid one.

Please try to use `-A` option of `cat` command.
  `cat -An $HOME/.config/deepl-translate-cli/setting.json`

If it still looks like a normal json, you can manually create and replace the json file.
Or you can use `-s |--source_lang` and `-t | --target_lang` to run without using `setting.json`
Example,  `echo "hello" | deepl-translate-cli --stdin -s EN -t JA`

**Comment by funcrab** [comment]
Thanks, I did the following.
```
$ cat -An $HOME/.config/deepl-translate-cli/setting.json
1	{$
2	  "source_lang": "EN",$
3	  "target_lang": "JA"$
4	}$
$ rm -f $HOME/.config/deepl-translate-cli/setting.json
$ echo "hello" | deepl-translate-cli --stdin -s EN -t JA
2021/09/23 01:49:51 unexpected end of JSON input
$ deepl-translate-cli -v
deepl-translate-cli version 0.0.8 (rev b64562f) [linux amd64 go1.16.6] [build at unkdown by unkdown]
$ cd $HOME/.local/bin
$ LANG=C ls -l deepl-translate-cli
-rwxr-xr-x 1 a a 6385664 Jul 22 21:43 deepl-translate-cli
$
```
It doesn't seem to work.
I used the following `tar xvf` and copied `deepl-translate-cli` to `~/.local/bin/`.
- https://github.com/Omochice/deepl-translate-cli/releases/download/v0.0.8/deepl-translate-cli_linux_x86_64.tar.gz

**Comment by Omochice** [comment]
Sorry for late reply.

I released v0.0.9.
It should work fine at least when specify `-s` and` -t`.

> Do I need any dependencies or libraries to make it work?

I don't use anything that depends on the outside, so you don't need anything else.

It's a CLI tool, so I think it works on both X / sway (I'm using manjaro i3, I'm new to sway).

The json looks like a valid one. However, just in case, try loading json with another lang / tool such as `jq`, `python`, `node`.
If it succeeds only with other tools, the problem is probably caused by a golang module.

**Comment by funcrab** [comment]
Thank you. I still can't seem to get it to work.
# Procedure 1
```
$ deepl-translate-cli -v
deepl-translate-cli version 0.0.9 (rev 926ce4e) [linux amd64 go1.16.8] [build at 2021-09-24T08:11:02Z by "goreleaser"]
$ cat $HOME/.config/deepl-translate-cli/setting.json | jq
{
  "source_lang": "EN",
  "target_lang": "JA"
}
$ echo "hello" | deepl-translate-cli --stdin -s EN -t JA
2021/09/25 10:06:23 unexpected end of JSON input (occurred while parse response)
$ 
```
I don't know if I'm doing it right, but I tried to build it.
It doesn't seem to work.
# Procedure 2
```
$ git clone https://github.com/Omochice/deepl-translate-cli
Cloning into 'deepl-translate-cli'...
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 90 (delta 46), reused 65 (delta 26), pack-reused 0
Receiving objects: 100% (90/90), 16.42 KiB | 1.82 MiB/s, done.
Resolving deltas: 100% (46/46), done.
$ cd deepl-translate-cli/
$ ls
LICENSE  README.md  go.mod  go.sum  main.go
$ go build
$ ls
LICENSE  README.md  deepl-translate-cli  go.mod  go.sum  main.go
$ ./deepl-translate-cli -v
deepl-translate-cli version dev (rev none) [linux amd64 go1.17.1] [build at unkdown by unkdown]
$ cat $HOME/.config/deepl-translate-cli/setting.json | jq
{
  "source_lang": "EN",
  "target_lang": "JA"
}
$ echo "hello" | ./deepl-translate-cli --stdin -s EN -t JA
2021/09/25 10:15:47 unexpected end of JSON input (occurred while parse response)
$ rm $HOME/.config/deepl-translate-cli/setting.json
$ echo "hello" | ./deepl-translate-cli --stdin -s EN -t JA
2021/09/25 10:21:48 unexpected end of JSON input (occurred while parse response)
$
```
I did Procedure 1 on a different machine in a sway environment and the same thing happened.
I'm not planning to do this right away, but I'll check again after a new Arch Linux installation without the window manager.
If you want, let me know if you have any more ideas.

**Comment by Omochice** [comment]
We got a very important information.
That is `(occurred while parse response)`.
We discussed about a loading `setting.json`.
Because, I thought that the error occurred there.
But we noticed the error occurred while parse response.

There are some possible causes.
- The token is invalid?
- The endpoint is invalid?
- others.

I will change to code to show the deepl's response in occurring error.

**Comment by Omochice** [comment]
I released [`v0.0.10`](https://github.com/Omochice/deepl-translate-cli/releases/tag/v0.0.10).
It show status if DeepL return other than 200~299 as status code.
It will be useful for resolving this problem.
And add `--pro` flag.
If you use DeepL as pro plan, use this flag.

**Comment by funcrab** [comment]
Thanks to you, I found the cause.
It seems that my account was not fully activated.
I re-registered and now I can translate.
```
$ echo hello | deepl-translate-cli --stdin
2021/10/03 19:41:02 Invalid response [403 Forbidden] Authorization failed. Please supply a valid auth_key parameter
$ 
$ # I updated my account.
$ nvim ~/.profile
$ source ~/.profile
$ echo "hello" | deepl-translate-cli --stdin -s EN -t JA
こんにちわ
$ echo "hello" | deepl-translate-cli --stdin
こんにちわ
$ cat $HOME/.config/deepl-translate-cli/setting.json | jq
{
  "source_lang": "EN",
  "target_lang": "JA"
}
```
Thanks for the useful tool.
